from pathlib import Path


def build_framer_prompt(*, dataset_path: Path | str, profile_path: Path | str) -> str:
    return f"""You are the EDA framer for the eda-artifacts MVP.

Dataset: {dataset_path}
Profile: {profile_path}

Your job is to define the first EDA task for the next agent. The next agent will
write SQL and a Vega-Lite chart spec. A later visual-review agent will inspect
the rendered chart image and write the report. You do not write SQL, chart specs,
or report text here. You only make the analytical task precise.

This is a constrained smoke trial, not open-ended dataset discovery. The target
variable is already known: monthly_rent_usd. The first EDA task must inspect the
target distribution before any modeling, regression, causality, or feature-driver
claim.

Return only JSON with exactly these fields:

- primary_question:
  One plain-English question the next agent must answer with the first rendered
  chart. It should be specific to monthly_rent_usd and answerable from a
  distribution chart.

- required_checks:
  Concrete requirements the next agent's SQL and result table must satisfy. Each
  item should be verifiable by inspecting the saved artifacts. Include the need
  to count listings by monthly_rent_usd bins and to keep the result compact
  enough for a chart.

- chart_requests:
  Concrete chart requirements for the next agent. State what the chart should
  show, what fields should appear on each axis, and why the chart is needed.
  For this trial, require rent_bin on the x axis and listing_count on the y axis.

- stop_conditions:
  Claims or actions that would make the next agent's output invalid. Include:
  no prediction claims, no regression claims, no causal claims, no price-driver
  claims, and no conclusion about modeling readiness before the rendered chart
  is visually reviewed.

Good output is operational: the next agent should be able to implement it without
guessing what SQL result, chart, or report boundary is expected.
"""


def build_artifact_builder_prompt(
    *,
    framing_path: Path | str,
    profile_path: Path | str,
    revision_request: str = "",
) -> str:
    revision_section = f"\nRevision request:\n{revision_request}\n" if revision_request else ""
    return f"""You are the artifact builder for eda-artifacts.

Framing artifact: {framing_path}
Dataset profile artifact: {profile_path}
{revision_section}
Write a read-only SQL query and a Vega-Lite chart spec.
The chart must visualize the target distribution of monthly_rent_usd before any
regression-style claim. Rendered images are generated by the harness from the
Vega-Lite spec.

SQL contract:
- Query the already-registered DuckDB table named dataset.
- Do not call read_csv, read_csv_auto, read_parquet, or any other file reader.
- Do not include file paths in SQL.
- Return a compact result table for the chart with exactly these columns:
  rent_bin, listing_count.

Chart contract:
- Return a single-view Vega-Lite object as a JSON string.
- Use top-level mark and encoding; do not use vconcat, hconcat, layer, facet, or repeat.
- Do not include a data key or file URL; the harness injects the SQL result rows.
- Use x.field = rent_bin and y.field = listing_count.

Return JSON with:
- sql
- chart_spec: a JSON-encoded string containing the Vega-Lite object
"""


def build_visual_reviewer_prompt() -> str:
    return """You are the visual reviewer for eda-artifacts.

You have been given a rendered chart image as an attachment. Use the image as
the evidence.

Inspect the rendered image first. Decide whether the chart is adequate for the
EDA task: it should be readable, show the monthly_rent_usd distribution, and make
the visible distribution shape interpretable.

Return JSON with:
- verdict: pass if the rendered chart is adequate, otherwise revise
- visual_findings: visible facts supported by the chart image
- required_revision: concrete changes needed if verdict is revise;
  use an empty string if verdict is pass
- report_markdown: a concise chart-grounded report based only on what you can see
  in the rendered chart image

Do not make prediction, regression, causality, or price-driver claims.
"""
